# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Google-StaticMaps
version:      0.1
version_from: lib/Geo/Google/StaticMaps.pm
installdirs:  site
requires:
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
